<a href="https://colab.research.google.com/github/blee8/work/blob/master/homework1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 1 - Berkeley STAT 157

Handout 1/22/2017, due 1/29/2017 by 4pm in Git by committing to your repository. Please ensure that you add the TA Git account to your repository.

1. Write all code in the notebook.
1. Write all text in the notebook. You can use MathJax to insert math or generic Markdown to insert figures (it's unlikely you'll need the latter). 
1. **Execute** the notebook and **save** the results.
1. To be safe, print the notebook as PDF and add it to the repository, too. Your repository should contain two files: ``homework1.ipynb`` and ``homework1.pdf``. 

The TA will return the corrected and annotated homework back to you via Git (please give `rythei` access to your repository).

In [ ]:
!pip install -U mxnet-cu101mkl==1.6.0  # updating mxnet to at least v1.6

     |████████████████████████████████| 711.0MB 26kB/s 
  Found existing installation: graphviz 0.10.1
    Uninstalling graphviz-0.10.1:
      Successfully uninstalled graphviz-0.10.1


In [ ]:
from mxnet import ndarray as nd
import mxnet as mx
import numpy as np
import time

## 1. Speedtest for vectorization

Your goal is to measure the speed of linear algebra operations for different levels of vectorization. You need to use `wait_to_read()` on the output to ensure that the result is computed completely, since NDArray uses asynchronous computation. Please see http://beta.mxnet.io/api/ndarray/_autogen/mxnet.ndarray.NDArray.wait_to_read.html for details. 

1. Construct two matrices $A$ and $B$ with Gaussian random entries of size $4096 \times 4096$. 
1. Compute $C = A B$ using matrix-matrix operations and report the time. 
1. Compute $C = A B$, treating $A$ as a matrix but computing the result for each column of $B$ one at a time. Report the time.
1. Compute $C = A B$, treating $A$ and $B$ as collections of vectors. Report the time.
1. Bonus question - what changes if you execute this on a GPU?

## practice

In [ ]:
#A = nd.random.normal(shape=(3,3))
A = nd.random.normal(shape=(3,3))
#A = nd.random.normal(0, 1, shape=(4096,4096))
#B = nd.random.normal(shape=(4096,4096))
B = nd.random.normal(shape=(3,3))

In [ ]:
print("A[0:3,0:3]= ", A[0:3,0:3])

A[0:3,0:3]=  
[[ 0.01900455  0.49163893  2.1766198 ]
 [ 2.280913   -0.3245641   0.07877541]
 [-0.15904595  0.7159357   0.57900923]]
<NDArray 3x3 @cpu(0)>


In [ ]:
tic = time.time()
#C = A * B
C = nd.dot(A, B)
C.wait_to_read()
print("Matrix by matrix: " + str(time.time() - tic) + " seconds")

Matrix by matrix: 2.1434521675109863 seconds


In [ ]:
print("C[0:3,0:3]= ", C[0:3,0:3])
print("A[0:3,0:3]= ", A[0:3,0:3])

C[0:3,0:3]=  
[[ 2.4561853   0.86430275  0.5033209 ]
 [-0.23248437  1.8802661   5.0104384 ]
 [ 0.58825064  0.7020131  -0.19487117]]
<NDArray 3x3 @cpu(0)>
A[0:3,0:3]=  
[[ 0.01900455  0.49163893  2.1766198 ]
 [ 2.280913   -0.3245641   0.07877541]
 [-0.15904595  0.7159357   0.57900923]]
<NDArray 3x3 @cpu(0)>


In [ ]:
tic = time.time()
D = A * B
#C = nd.dot(A, B)
#D = np.matmul(A,B)
#D.wait_to_read()
#print("Matrix by matrix: " + str(time.time() - tic) + " seconds")

In [ ]:
print("D[0:2,0:2]= ", D )
print("A[0,0]= ", A[0:2,0:2])

D[0:2,0:2]=  
[[-3.12780053e-03  4.78354901e-01  4.78318453e+00]
 [-3.59138817e-01 -3.50417763e-01  4.28863056e-03]
 [-1.85358793e-01  1.03613526e-01  1.15660436e-01]]
<NDArray 3x3 @cpu(0)>
A[0,0]=  
[[ 0.01900455  0.49163893]
 [ 2.280913   -0.3245641 ]]
<NDArray 2x2 @cpu(0)>


In [ ]:
tic = time.time()
for i in range A.size(1,0)

In [ ]:
X = np.arange(4).reshape(2, 2)
X

array([[0, 1],
       [2, 3]])

In [ ]:
X.shape
X.size
type(X)

numpy.ndarray

In [ ]:
X = nd.arange(4).reshape(2, 2)
X


[[0. 1.]
 [2. 3.]]
<NDArray 2x2 @cpu(0)>

In [ ]:
type(X)

numpy.ndarray

In [ ]:
#X=np.array([2,2],[3,3])
#u = np.array([[3, -4, 3], [3, 5, 5]] )
#u = np.array([[1,2],[5,2]])
u = np.array([[[1,1],[2,2]],[[5,5],[2,6]]])
print(u.shape)
print(u)
print(type(u))

(2, 2, 2)
[[[1 1]
  [2 2]]

 [[5 5]
  [2 6]]]
<class 'numpy.ndarray'>


In [ ]:
X = nd.arange(8).reshape(2, 2, 2)
print(X.shape)
print(X)
print(type(X))

(2, 2, 2)

[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]
<NDArray 2x2x2 @cpu(0)>
<class 'mxnet.ndarray.ndarray.NDArray'>


In [ ]:
Y = nd.arange(8).reshape(2,2,2)
Y


[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]
<NDArray 2x2x2 @cpu(0)>

In [ ]:
Z = nd.dot(X,Y)
Z


[[[[ 4.  5.]
   [ 6.  7.]]

  [[12. 17.]
   [22. 27.]]]


 [[[20. 29.]
   [38. 47.]]

  [[28. 41.]
   [54. 67.]]]]
<NDArray 2x2x2x2 @cpu(0)>

## nd.array practice

In [ ]:
A = nd.array([[2, 4], [3, 1]])
B = nd.array([[3, 1], [2, 5]])

In [ ]:
AA = A.asnumpy()
BB = B.asnumpy()

In [ ]:
AA
type(AA)

numpy.ndarray

In [ ]:
A


[[2. 4.]
 [3. 1.]]
<NDArray 2x2 @cpu(0)>

In [ ]:
A
B


[[3. 1.]
 [2. 5.]]
<NDArray 2x2 @cpu(0)>

In [ ]:
nd.dot(A,B)


[[14. 22.]
 [11.  8.]]
<NDArray 2x2 @cpu(0)>

In [ ]:
A*B


[[6. 4.]
 [6. 5.]]
<NDArray 2x2 @cpu(0)>

In [ ]:
#C= np.matmul(A,B)
C= np.matmul(AA,BB)
type(C)
C.shape
#C.size
print(C)

[[14. 22.]
 [11.  8.]]


In [ ]:
import numpy
# Two matrices are initialized by value
x = numpy.array([[1, 2], [4, 5]])
y = numpy.array([[7, 8], [9, 10]])
print(x, y)
#  add()is used to add matrices
print ("Addition of two matrices: ")
print (numpy.add(x,y))
# subtract()is used to subtract matrices
print ("Subtraction of two matrices : ")
print (numpy.subtract(x,y))
# divide()is used to divide matrices
print ("Matrix Division : ")
print (numpy.divide(x,y))
print ("Multiplication of two matrices: ")
print (numpy.multiply(x,y))
print ("The product of two matrices : ")
print (numpy.dot(x,y))
print ("square root is : ")
print (numpy.sqrt(x))
print ("The summation of elements : ")
print (numpy.sum(y))
print ("The column wise summation  : ")
print (numpy.sum(y,axis=0))
print ("The row wise summation: ")
print (numpy.sum(y,axis=1))
# using "T" to transpose the matrix
print ("Matrix transposition : ")
print (x.T)

[[1 2]
 [4 5]] [[ 7  8]
 [ 9 10]]
Addition of two matrices: 
[[ 8 10]
 [13 15]]
Subtraction of two matrices : 
[[-6 -6]
 [-5 -5]]
Matrix Division : 
[[0.14285714 0.25      ]
 [0.44444444 0.5       ]]
Multiplication of two matrices: 
[[ 7 16]
 [36 50]]
The product of two matrices : 
[[25 28]
 [73 82]]
square root is : 
[[1.         1.41421356]
 [2.         2.23606798]]
The summation of elements : 
34
The column wise summation  : 
[16 18]
The row wise summation: 
[15 19]
Matrix transposition : 
[[1 4]
 [2 5]]


In [ ]:
np.matmul(x,y)

array([[25, 28],
       [73, 82]])

In [ ]:
np.dot(x,y)

array([[25, 28],
       [73, 82]])

In [ ]:
x*y

array([[ 7, 16],
       [36, 50]])

In [ ]:
np.multiply(x,y)

array([[ 7, 16],
       [36, 50]])

## solution

In [ ]:
A = nd.random.normal(shape=(4096,4096))
B = nd.random.normal(shape=(4096,4096))
A.shape

(4096, 4096)

In [ ]:
tic = time.time()
C = nd.dot(A,B)
C.wait_to_read()
print("Matrix by matrix: " + str(time.time() - tic) + " seconds")

Matrix by matrix: 2.2000935077667236 seconds


In [ ]:
tic = time.time()
C = nd.dot(A,B)

In [ ]:
C = nd.empty((4096, 4096))
tic = time.time()
for i in range(4096):
    C[:, i] = nd.dot(A, B[:, i])
C.wait_to_read()
print("Matrix by vector: " + str(time.time() - tic) + " seconds")

Matrix by vector: 67.78497171401978 seconds


In [ ]:
C = nd.empty((4096, 4096))
tic = time.time()
for i in range(4096):
    for j in range(4096):
        C[i,j] = nd.dot(A[i, :], B[:, j])
C.wait_to_read()
print("Vector by vector: " + str(time.time() - tic) + " seconds")

## 2. Semidefinite Matrices

Assume that $A \in \mathbb{R}^{m \times n}$ is an arbitrary matrix and that $D \in \mathbb{R}^{n \times n}$ is a diagonal matrix with nonnegative entries. 

1. Prove that $B = A D A^\top$ is a positive semidefinite matrix. 
1. When would it be useful to work with $B$ and when is it better to use $A$ and $D$?

## 3. MXNet on GPUs

1. Install GPU drivers (if needed)
1. Install MXNet on a GPU instance
1. Display `!nvidia-smi`
1. Create a $2 \times 2$ matrix on the GPU and print it. See http://d2l.ai/chapter_deep-learning-computation/use-gpu.html for details.

In [ ]:
!nvidia-smi

Mon Jul 13 08:52:15 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.36.06    Driver Version: 418.67       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:04.0 Off |                    0 |
| N/A   56C    P8    30W / 149W |      0MiB / 11441MiB |      0%      Default |
|                               |                      |                 ERR! |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
x = nd.ones((2, 2), ctx=mx.gpu())
x


[[1. 1.]
 [1. 1.]]
<NDArray 2x2 @gpu(0)>

In [ ]:
AA = nd.random.normal(shape=(4096,4096),ctx=mx.gpu())
BB = nd.random.normal(shape=(4096,4096),ctx=mx.gpu())

In [ ]:
tic = time.time()
C = nd.dot(AA,BB)
C.wait_to_read()
print("Matrix by matrix: " + str(time.time() - tic) + " seconds")

Matrix by matrix: 0.06453084945678711 seconds


In [ ]:
C = nd.empty((4096, 4096))
tic = time.time()
for i in range(4096):
    C[:, i] = nd.dot(AA, BB[:, i])
C.wait_to_read()
print("Matrix by vector: " + str(time.time() - tic) + " seconds")

Matrix by vector: 4.284566879272461 seconds


In [ ]:
C = nd.empty((4096, 4096))
tic = time.time()
for i in range(4096):
    for j in range(4096):
        C[i,j] = nd.dot(A[i, :], B[:, j])
C.wait_to_read()
print("Vector by vector: " + str(time.time() - tic) + " seconds")

## 4. NDArray and NumPy 

Your goal is to measure the speed penalty between MXNet Gluon and Python when converting data between both. We are going to do this as follows:

1. Create two Gaussian random matrices $A, B$ of size $4096 \times 4096$ in NDArray. 
1. Compute a vector $\mathbf{c} \in \mathbb{R}^{4096}$ where $c_i = \|A B_{i\cdot}\|^2$ where $\mathbf{c}$ is a **NumPy** vector.

To see the difference in speed due to Python perform the following two experiments and measure the time:

1. Compute $\|A B_{i\cdot}\|^2$ one at a time and assign its outcome to $\mathbf{c}_i$ directly.
1. Use an intermediate storage vector $\mathbf{d}$ in NDArray for assignments and copy to NumPy at the end.

In [ ]:
A = nd.random.normal(shape=(4096, 4096),ctx=mx.gpu())
B = nd.random.normal(shape=(4096, 4096),ctx=mx.gpu())
c = np.empty(4096)
tic = time.time()
for i in range(4096):
    c[i] = (nd.norm(nd.dot(A, B[:, i])).asscalar())**2
print("One at a time: " + str(time.time() - tic) + " seconds")

One at a time: 6.499990463256836 seconds


In [ ]:
d = nd.empty(4096)
tic = time.time()
for i in range(4096):
    d[i] = nd.norm(nd.dot(A, B[:, i]))**2
c = d.asnumpy()
print("Convert at end: " + str(time.time() - tic) + " seconds")

Convert at end: 4.857295989990234 seconds


## 5. Memory efficient computation

We want to compute $C \leftarrow A \cdot B + C$, where $A, B$ and $C$ are all matrices. Implement this in the most memory efficient manner. Pay attention to the following two things:

1. Do not allocate new memory for the new value of $C$.
1. Do not allocate new memory for intermediate results if possible.

In [ ]:
A = nd.random.normal(shape=(100,100),ctx=mx.gpu())
type(A)

mxnet.ndarray.ndarray.NDArray

In [ ]:
A = nd.random.normal(shape=(100,100))
B = nd.random.normal(shape=(100,100))
C = nd.random.normal(shape=(100,100))
C += nd.dot(A,B)
type(C)

mxnet.ndarray.ndarray.NDArray

## 6. Broadcast Operations

In order to perform polynomial fitting we want to compute a design matrix $A$ with 

$$A_{ij} = x_i^j$$

Our goal is to implement this **without a single for loop** entirely using vectorization and broadcast. Here $1 \leq j \leq 20$ and $x = \{-10, -9.9, \ldots 10\}$. Implement code that generates such a matrix.

In [ ]:
 x = nd.arange(start=-10, stop=10.1, step=0.1).reshape((201, 1))
 x


[[-10.        ]
 [ -9.9       ]
 [ -9.8       ]
 [ -9.7       ]
 [ -9.6       ]
 [ -9.5       ]
 [ -9.4       ]
 [ -9.3       ]
 [ -9.2       ]
 [ -9.1       ]
 [ -9.        ]
 [ -8.9       ]
 [ -8.8       ]
 [ -8.7       ]
 [ -8.6       ]
 [ -8.5       ]
 [ -8.4       ]
 [ -8.3       ]
 [ -8.2       ]
 [ -8.1       ]
 [ -8.        ]
 [ -7.8999996 ]
 [ -7.8       ]
 [ -7.7       ]
 [ -7.6       ]
 [ -7.5       ]
 [ -7.3999996 ]
 [ -7.3       ]
 [ -7.2       ]
 [ -7.1       ]
 [ -7.        ]
 [ -6.8999996 ]
 [ -6.8       ]
 [ -6.7       ]
 [ -6.6       ]
 [ -6.5       ]
 [ -6.3999996 ]
 [ -6.3       ]
 [ -6.2       ]
 [ -6.1       ]
 [ -6.        ]
 [ -5.9       ]
 [ -5.7999997 ]
 [ -5.7       ]
 [ -5.6       ]
 [ -5.5       ]
 [ -5.4       ]
 [ -5.2999997 ]
 [ -5.2       ]
 [ -5.1       ]
 [ -5.        ]
 [ -4.9       ]
 [ -4.7999997 ]
 [ -4.7       ]
 [ -4.6       ]
 [ -4.5       ]
 [ -4.4       ]
 [ -4.2999997 ]
 [ -4.2       ]
 [ -4.1       ]
 [ -4.        ]
 [ -3.9       ]
 [ -3.7

In [ ]:
j = nd.arange(start=1, stop=21, step=1.0).reshape((1, 20))
j.shape

(1, 20)

In [ ]:
print(x ** j)


[[-1.0000000e+01  1.0000000e+02 -1.0000000e+03 ...  9.9999998e+17
  -1.0000000e+19  1.0000000e+20]
 [-9.8999996e+00  9.8009995e+01 -9.7029889e+02 ...  8.3451318e+17
  -8.2616803e+18  8.1790629e+19]
 [-9.8000002e+00  9.6040001e+01 -9.4119208e+02 ...  6.9513558e+17
  -6.8123289e+18  6.6760824e+19]
 ...
 [ 9.8000011e+00  9.6040024e+01  9.4119232e+02 ...  6.9513681e+17
   6.8123415e+18  6.6760952e+19]
 [ 9.8999996e+00  9.8009995e+01  9.7029889e+02 ...  8.3451318e+17
   8.2616803e+18  8.1790629e+19]
 [ 1.0000000e+01  1.0000000e+02  1.0000000e+03 ...  9.9999998e+17
   1.0000000e+19  1.0000000e+20]]
<NDArray 201x20 @cpu(0)>


In [ ]:
Xij = x ** j

In [ ]:
Xij.shape

(201, 20)

In [ ]:
print(Xij[0:5,:3])


[[  -10.         100.       -1000.      ]
 [   -9.9         98.009995  -970.2989  ]
 [   -9.8         96.04      -941.1921  ]
 [   -9.7         94.09      -912.673   ]
 [   -9.6         92.16      -884.7361  ]]
<NDArray 5x3 @cpu(0)>
