<a href="https://colab.research.google.com/github/blee8/work/blob/master/homework2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Homework 2 - Berkeley STAT 157

Handout 1/29/2019, due 2/5/2019 by 4pm in Git by committing to your repository.

In [4]:
#!pip install -U mxnet-cu101mkl==1.6.0  # updating mxnet to at least v1.6
!pip install mxnet==1.6.0

     |████████████████████████████████| 68.7MB 48kB/s 


In [2]:
from mxnet import nd, autograd, gluon

/usr/local/lib/python2.7/dist-packages/mxnet/numpy_op_signature.py:61: UserWarning: Some mxnet.numpy operator signatures may not be displayed consistently with their counterparts in the official NumPy package due to too-low Python version 2.7.17 (default, Apr 15 2020, 17:20:14) 
[GCC 7.5.0]. Python >= 3.5 is required to make the signatures display correctly.
  .format(str(sys.version)))


# 1. Multinomial Sampling

Implement a sampler from a discrete distribution from scratch, mimicking the function `mxnet.ndarray.random.multinomial`. Its arguments should be a vector of probabilities $p$. You can assume that the probabilities are normalized, i.e. tha they sum up to $1$. Make the call signature as follows:

```
samples = sampler(probs, shape) 

probs   : An ndarray vector of size n of nonnegative numbers summing up to 1
shape   : A list of dimensions for the output
samples : Samples from probs with shape matching shape
```

Hints:

1. Use `mxnet.ndarray.random.uniform` to get a sample from $U[0,1]$.
1. You can simplify things for `probs` by computing the cumulative sum over `probs`.

In [3]:
from mxnet import ndarray as nd

/usr/local/lib/python2.7/dist-packages/mxnet/numpy_op_signature.py:61: UserWarning: Some mxnet.numpy operator signatures may not be displayed consistently with their counterparts in the official NumPy package due to too-low Python version 2.7.17 (default, Apr 15 2020, 17:20:14) 
[GCC 7.5.0]. Python >= 3.5 is required to make the signatures display correctly.
  .format(str(sys.version)))


In [3]:
def sampler(probs, shape):
    ## Add your codes here
    return nd.zeros(shape)

# a simple test
sampler(nd.array([0.2, 0.3, 0.5]), (2,3))


[[0. 0. 0.]
 [0. 0. 0.]]
<NDArray 2x3 @cpu(0)>

In [5]:
    sum = nd.zeros(shape=(2,2))
sum


[[0. 0.]
 [0. 0.]]
<NDArray 2x2 @cpu(0)>

In [22]:
def sampler1(probs, shape):
    ## Add your codes here
    #print(probs)
    #sum = nd.zeros(shape)
    sum = probs
    print sum
    return sum 

In [9]:
U = nd.random.uniform(shape=(10))
type(U)
U


[0.5488135  0.5928446  0.71518934 0.84426576 0.60276335 0.8579456
 0.5448832  0.8472517  0.4236548  0.6235637 ]
<NDArray 10 @cpu(0)>

In [8]:
sampler1(U, (2,5))

NameError: ignored

In [12]:
s = nd.zeros(shape=(2,2))
print(s)
s  = U[0:4]
s


[[0. 0.]
 [0. 0.]]
<NDArray 2x2 @cpu(0)>



[0.5488135  0.5928446  0.71518934 0.84426576]
<NDArray 4 @cpu(0)>

# 2. Central Limit Theorem

Let's explore the Central Limit Theorem when applied to text processing. 

* Download [https://www.gutenberg.org/ebooks/84](https://www.gutenberg.org/files/84/84-0.txt) from Project Gutenberg 
* Remove punctuation, uppercase / lowercase, and split the text up into individual tokens (words).
* For the words `a`, `and`, `the`, `i`, `is` compute their respective counts as the book progresses, i.e. 
    $$n_\mathrm{the}[i] = \sum_{j = 1}^i \{w_j = \mathrm{the}\}$$
* Plot the proportions $n_\mathrm{word}[i] / i$ over the document in one plot.
* Find an envelope of the shape $O(1/\sqrt{i})$ for each of these five words. (Hint, check the last page of the [sampling notebook](http://courses.d2l.ai/berkeley-stat-157/slides/1_24/sampling.pdf))
* Why can we **not** apply the Central Limit Theorem directly? 
* How would we have to change the text for it to apply? 
* Why does it still work quite well?

In [ ]:
filename = gluon.utils.download('https://www.gutenberg.org/files/84/84-0.txt')
with open(filename) as f:
    book = f.read()
print(book[0:100])

## Add your codes here


Project Gutenberg's Frankenstein, by Mary Wollstonecraft (Godwin) Shelley

This eBook is for the u


## 3. Denominator-layout notation

We used the numerator-layout notation for matrix calculus in class, now let's examine the denominator-layout notation.

Given $x, y\in\mathbb R$, $\mathbf x\in\mathbb R^n$ and $\mathbf y \in \mathbb R^m$, we have

$$
\frac{\partial y}{\partial \mathbf{x}}=\begin{bmatrix}
\frac{\partial y}{\partial x_1}\\
\frac{\partial y}{\partial x_2}\\
\vdots\\
\frac{\partial y}{\partial x_n}
\end{bmatrix},\quad 
\frac{\partial \mathbf y}{\partial {x}}=\begin{bmatrix}
\frac{\partial y_1}{\partial x}, 
\frac{\partial y_2}{\partial x}, 
\ldots,
\frac{\partial y_m}{\partial x}
\end{bmatrix}
$$

and 

$$
\frac{\partial \mathbf y}{\partial \mathbf{x}}
=\begin{bmatrix}
\frac{\partial \mathbf y}{\partial {x_1}}\\
\frac{\partial \mathbf y}{\partial {x_2}}\\
\vdots\\
\frac{\partial \mathbf y}{\partial {x_3}}\\
\end{bmatrix}
=\begin{bmatrix}
\frac{\partial y_1}{\partial x_1}, 
\frac{\partial y_2}{\partial x_1},
\ldots,
\frac{\partial y_m}{\partial x_1}
\\ 
\frac{\partial y_1}{\partial x_2},
\frac{\partial y_2}{\partial x_2},
\ldots,
\frac{\partial y_m}{\partial x_2}\\ 
\vdots\\
\frac{\partial y_1}{\partial x_n},
\frac{\partial y_2}{\partial x_n},
\ldots,
\frac{\partial y_m}{\partial x_n}
\end{bmatrix}
$$

Questions: 

1. Assume $\mathbf  y = f(\mathbf u)$ and $\mathbf u = g(\mathbf x)$, write down the chain rule for $\frac {\partial\mathbf  y}{\partial\mathbf x}$
2. Given $\mathbf X \in \mathbb R^{m\times n},\ \mathbf w \in \mathbb R^n, \ \mathbf y \in \mathbb R^m$, assume $z = \| \mathbf X \mathbf w - \mathbf y\|^2$, compute $\frac{\partial z}{\partial\mathbf w}$.

## 4. Numerical Precision

Given scalars `x` and `y`, implement the following `log_exp` function such that it returns 
$$-\log\left(\frac{e^x}{e^x+e^y}\right)$$.

In [ ]:
def log_exp(x, y):
    ## add your solution here
    pass

Test your codes with normal inputs:

In [ ]:
x, y = nd.array([2]), nd.array([3])
z = log_exp(x, y)
z

Now implement a function to compute $\partial z/\partial x$ and $\partial z/\partial y$ with `autograd`

In [ ]:
def grad(forward_func, x, y): 
    ## Add your codes here
    print('x.grad =', x.grad)
    print('y.grad =', y.grad)

Test your codes, it should print the results nicely. 

In [ ]:
grad(log_exp, x, y)

x.grad = None
y.grad = None


But now let's try some "hard" inputs

In [ ]:
x, y = nd.array([50]), nd.array([100])
grad(log_exp, x, y)

x.grad = None
y.grad = None


Does your code return correct results? If not, try to understand the reason. (Hint, evaluate `exp(100)`). Now develop a new function `stable_log_exp` that is identical to `log_exp` in math, but returns a more numerical stable result.

In [ ]:
def stable_log_exp(x, y):
    ## Add your codes here
    pass

grad(stable_log_exp, x, y)

x.grad = None
y.grad = None
